### ISSUE TITLE
Issue in creating the FHIR Server sample environment

### ISSUE THREAD

**Issue by ToorMaryam** [microsoft/fhir-server-samples#100]
Hi,

We are having an issue when creating the FHIR Server sample environment. We tried below commands but in both cases, we are getting errors. Can you please guide us?

.\Create-FhirServerSamplesEnvironment.ps1 -EnvironmentName myfhirdemo1 -UsePaaS $true
.\Create-FhirServerSamplesEnvironment.ps1 -EnvironmentName myfhirdemo1 -UsePaaS $false

Below are the errors:

PS E:\fhir-server-samples\deploy\scripts> .\Create-FhirServerSamplesEnvironment.ps1 -EnvironmentName myfhirdemo1 -UsePaaS $false                  Current context is user: <user>
myfhirdemo1
FhirServer PS module is loaded
Creating keyvault with the name myfhirdemo1-ts
Current context is user: <user>
Adding permission to keyvault for <ID>
Ensuring API application exists
Checking if UserPrincipalName exists
User not, will create.
The property 'SecretValueText' cannot be found on this object. Verify that the property exists.
At E:\fhir-server-samples\deploy\scripts\Create-FhirServerSamplesEnvironment.ps1:154 char:1
+ $confidentialClientId = (Get-AzKeyVaultSecret -VaultName "${Environme ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], PropertyNotFoundException
    + FullyQualifiedErrorId : PropertyNotFoundStrict

The property 'SecretValueText' cannot be found on this object. Verify that the property exists.
At E:\fhir-server-samples\deploy\scripts\Create-FhirServerSamplesEnvironment.ps1:155 char:1
+ $confidentialClientSecret = (Get-AzKeyVaultSecret -VaultName "${Envir ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], PropertyNotFoundException
    + FullyQualifiedErrorId : PropertyNotFoundStrict

The property 'SecretValueText' cannot be found on this object. Verify that the property exists.
At E:\fhir-server-samples\deploy\scripts\Create-FhirServerSamplesEnvironment.ps1:156 char:1
+ $serviceClientId = (Get-AzKeyVaultSecret -VaultName "${EnvironmentNam ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], PropertyNotFoundException
    + FullyQualifiedErrorId : PropertyNotFoundStrict

The property 'SecretValueText' cannot be found on this object. Verify that the property exists.
At E:\fhir-server-samples\deploy\scripts\Create-FhirServerSamplesEnvironment.ps1:157 char:1
+ $serviceClientSecret = (Get-AzKeyVaultSecret -VaultName "${Environmen ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], PropertyNotFoundException
    + FullyQualifiedErrorId : PropertyNotFoundStrict

Get-AzureADServicePrincipal : Error occurred while executing GetServicePrincipals
Code: Request_UnsupportedQuery
Message: Unsupported or invalid query filter clause specified for property 'appId' of resource 'ServicePrincipal'.
RequestId: <id>
DateTimeStamp: Fri, 06 Nov 2020 07:27:03 GMT
HttpStatusCode: BadRequest
HttpStatusDescription: Bad Request
HttpResponseStatus: Completed
At E:\fhir-server-samples\deploy\scripts\Create-FhirServerSamplesEnvironment.ps1:158 char:27
+ ... ObjectId = (Get-AzureADServicePrincipal -Filter "AppId eq '$serviceCl ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-AzureADServicePrincipal], ApiException
    + FullyQualifiedErrorId : Microsoft.Open.AzureAD16.Client.ApiException,Microsoft.Open.AzureAD16.PowerShell.GetServ
   icePrincipal

The property 'SecretValueText' cannot be found on this object. Verify that the property exists.
At E:\fhir-server-samples\deploy\scripts\Create-FhirServerSamplesEnvironment.ps1:159 char:1
+ $dashboardUserUpn  = (Get-AzKeyVaultSecret -VaultName "${EnvironmentN ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], PropertyNotFoundException
    + FullyQualifiedErrorId : PropertyNotFoundStrict

Get-AzureADUser : Error occurred while executing GetUsers
Code: Request_UnsupportedQuery
Message: Unsupported or invalid query filter clause specified for property 'userPrincipalName' of resource 'User'.
RequestId: <id>
DateTimeStamp: Fri, 06 Nov 2020 07:27:07 GMT
HttpStatusCode: BadRequest
HttpStatusDescription: Bad Request
HttpResponseStatus: Completed
At E:\fhir-server-samples\deploy\scripts\Create-FhirServerSamplesEnvironment.ps1:160 char:22
+ ... dUserOid = (Get-AzureADUser -Filter "UserPrincipalName eq '$dashboard ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-AzureADUser], ApiException
    + FullyQualifiedErrorId : Microsoft.Open.AzureAD16.Client.ApiException,Microsoft.Open.AzureAD16.PowerShell.GetUser

The property 'SecretValueText' cannot be found on this object. Verify that the property exists.
At E:\fhir-server-samples\deploy\scripts\Create-FhirServerSamplesEnvironment.ps1:161 char:1
+ $dashboardUserPassword  = (Get-AzKeyVaultSecret -VaultName "${Environ ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], PropertyNotFoundException
    + FullyQualifiedErrorId : PropertyNotFoundStrict

The property 'SecretValueText' cannot be found on this object. Verify that the property exists.
At E:\fhir-server-samples\deploy\scripts\Create-FhirServerSamplesEnvironment.ps1:162 char:1
+ $publicClientId = (Get-AzKeyVaultSecret -VaultName "${EnvironmentName ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], PropertyNotFoundException
    + FullyQualifiedErrorId : PropertyNotFoundStrict

You cannot call a method on a null-valued expression.
At E:\fhir-server-samples\deploy\scripts\Create-FhirServerSamplesEnvironment.ps1:166 char:1
+ $accessPolicies += @{ "objectId" = $serviceClientObjectId.ToString()  ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull

You cannot call a method on a null-valued expression.
At E:\fhir-server-samples\deploy\scripts\Create-FhirServerSamplesEnvironment.ps1:167 char:1
+ $accessPolicies += @{ "objectId" = $dashboardUserOid.ToString() }
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull

New-AzResourceGroupDeployment : Cannot bind argument to parameter 'aadDashboardClientId' because it is null.
At E:\fhir-server-samples\deploy\scripts\Create-FhirServerSamplesEnvironment.ps1:187 char:323
+ ... ity $aadAuthority -aadDashboardClientId $confidentialClientId -aadDas ...
+                                             ~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [New-AzResourceGroupDeployment], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.Azure.Commands.ResourceManager.
   Cmdlets.Implementation.NewAzureResourceGroupDeploymentCmdlet

Warming up site...
Invoke-WebRequest : The remote name could not be resolved: 'myfhirdemo1srvr.azurewebsites.net'
At E:\fhir-server-samples\deploy\scripts\Create-FhirServerSamplesEnvironment.ps1:190 char:1
+ Invoke-WebRequest -Uri "${fhirServerUrl}/metadata" | Out-Null
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-WebRequest], WebExc
   eption
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand

Invoke-WebRequest : The remote name could not be resolved: 'myfhirdemo1imp.azurewebsites.net'
At E:\fhir-server-samples\deploy\scripts\Create-FhirServerSamplesEnvironment.ps1:192 char:1
+ Invoke-WebRequest -Uri $functionAppUrl | Out-Null
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-WebRequest], WebExc
   eption
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand

**Comment by sirjun05** [comment]
I am having the same errors. Can someone put a guide on how to setup the sample environment properly, thanks

**Comment by marta314** [comment]
Same problem here:
Skipping Reply URL add. Already added.
The property 'SecretValueText' cannot be found on this object. Verify that the property exists.
At C:\fhir-server-samples\deploy\scripts\Create-FhirServerSamplesEnvironment.ps1:162 char:1
+ $publicClientId = (Get-AzKeyVaultSecret -VaultName "${EnvironmentName ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], PropertyNotFoundException
    + FullyQualifiedErrorId : PropertyNotFoundStrict
 
New-AzResourceGroupDeployment : 18:34:13 - Error: Code=InvalidDeploymentParameterValue; Message=The value of deployment parameter 'smartAppClientId' is null. Please specify the value or use the parameter reference. See https://aka.ms/resource-ma
nager-parameter-files for details.
At C:\fhir-server-samples\deploy\scripts\Create-FhirServerSamplesEnvironment.ps1:187 char:1
+ New-AzResourceGroupDeployment -TemplateUri $sandboxTemplate -environm ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [New-AzResourceGroupDeployment], Exception
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.ResourceManager.Cmdlets.Implementation.NewAzureResourceGroupDeploymentCmdlet
 
New-AzResourceGroupDeployment : The deployment validation failed
At C:\fhir-server-samples\deploy\scripts\Create-FhirServerSamplesEnvironment.ps1:187 char:1
+ New-AzResourceGroupDeployment -TemplateUri $sandboxTemplate -environm ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [New-AzResourceGroupDeployment], InvalidOperationException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.ResourceManager.Cmdlets.Implementation.NewAzureResourceGroupDeploymentCmdlet

**Comment by ginalee-dotcom** [comment]
What are the steps you are taking to produce this error? Would you be able to lay out the commands you are running (including your subscription name, environment name, etc) step-by-step in detail? I was not able to reproduce these errors and would like to.
It appears that you are missing certain fields/properties on your KeyVault, or they are invalid. These are the fields that retrieve SecretValueText, so check that you are logged in to the right account and subscription, and that you have valid fields/properties for the following on your KeyVault:
```
confidentialClientId
confidentialClientSecret
serviceClientId
serviceClientSecret
serviceClientObjectId
dashboardUserUpn
dashboardUserOid
dashboardUserPassword 
publicClientId
``` 
Also would you be able to post your PS version (`$PSVersionTable.PSVersion`) and Az module version (`Get-InstalledModule -Name Az`)? Not that these would cause the errors, but for reference.
