### ISSUE TITLE
Script issue

### ISSUE THREAD

**Issue by v-srinivas** [microsoft/fhir-server-samples#108]
Create-FhirServerSamplesEnvironment.ps1: Cannot validate argument on parameter 'EnvironmentName'. The character length of the 14 argument is too long. Shorten the character length of the argument so it is fewer than or equal to "12" characters, and then try the command again.

**Comment by ginalee-dotcom** [comment]
@v-srinivas Can you elaborate on the issue you are having? Is there a problem with keeping the character length fewer than or equal to 12 characters?
