### ISSUE TITLE
[Bug] Invalid deploy script-url fetched from fhir-server repository

### ISSUE THREAD

**Issue by alsami** [microsoft/fhir-server-samples#111]
While setting up the OS variant with SQL server, I noticed that there are some problems with the latest version.

The script that is used as [deploy-script for SQL server variant](https://github.com/microsoft/fhir-server-samples/blob/master/deploy/scripts/Create-FhirServerSamplesEnvironment.ps1#L135) is invalid and does not exist anymore.

Apparently they have been merged into [one file](https://github.com/microsoft/fhir-server/blob/master/samples/templates/default-azuredeploy.json).

Proposed solution:
- Update the script reference
  - if possible, use a tagged version of the repository
- Add another parameter for the `solutionType` [here](https://github.com/microsoft/fhir-server-samples/blob/cbca4798876d9d9dcf406a2b8c749ff62e452492/deploy/templates/azuredeploy-sandbox.json#L231), which may be passed through and defaults to `FhirServerCosmosDB`. It should provide same values as the [target template](https://github.com/microsoft/fhir-server/blob/master/samples/templates/default-azuredeploy.json#L102)
- Last but not least, the condition [here](https://github.com/microsoft/fhir-server-samples/blob/cbca4798876d9d9dcf406a2b8c749ff62e452492/deploy/templates/azuredeploy-sandbox.json#L236) must be changed, since the file-name does not contain "sql" anymore

I'd be happy to send a PR your way, but there was another problem in the fire-server repository when using SQL, for which I've created a [PR](https://github.com/microsoft/fhir-server/pull/1516) already.

**Comment by ginalee-dotcom** [comment]
Thank you for the feedback! We will update our scripts with reference to your proposed solutions.
