### ISSUE TITLE
Unable to deploy with deploy scripts 

### ISSUE THREAD

**Issue by cunninghamb505** [microsoft/fhir-server-samples#112]
When following the instructions I am getting multiple errors when trying to deploy from local or from the shell.  Log below

**_Ensuring API application exists
Checking if UserPrincipalName exists
User not, will create.
InvalidOperation: /home/fhirdeploy/fhir-server-samples/deploy/scripts/Create-FhirServerSamplesAuthConfig.ps1:170
Line |
 170 |      $password = [System.Web.Security.Membership]::GeneratePassword(16 …
     |                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Unable to find type [System.Web.Security.Membership].

ConvertTo-SecureString: /fhirdeploy/fhir-server-samples/deploy/scripts/Create-FhirServerSamplesAuthConfig.ps1:171
Line |
 171 |      $passwordSecureString = ConvertTo-SecureString $password -AsPlain …
     |                                                     ~~~~~~~~~
     | Cannot bind argument to parameter 'String' because it is null.

New-AzureADUser: /home/fhirdeploy/fhir-server-samples/deploy/scripts/Create-FhirServerSamplesAuthConfig.ps1:183
Line |
 183 |  …  $aadUser = New-AzureADUser -DisplayName $userId -PasswordProfile $Pa …
     |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Error occurred while executing NewUser  Code: Request_BadRequest Message: A password must be specified to create a new user. RequestId: *************43704517 DateTimeStamp: Sun, 20 Dec 2020 17:57:30 GMT
     | HttpStatusCode: BadRequest HttpStatusDescription: Bad Request HttpResponseStatus: Completed

Set-AzKeyVaultSecret: /home//fhirdeploy/fhir-server-samples/deploy/scripts/Create-FhirServerSamplesAuthConfig.ps1:188
Line |
 188 |  … e -Name "$userId-password" -SecretValue $passwordSecureString | Out-N …
     |                                            ~~~~~~~~~~~~~~~~~~~~~
     | Cannot bind argument to parameter 'SecretValue' because it is null.

Exception: /home//fhirdeploy/fhir-server-samples/deploy/scripts/fhir-server/samples/scripts/PowerShell/FhirServer/Public/Set-FhirServerUserAppRoleAssignments.ps1:43
Line |
  43 |          throw "User not found"
     |          ~~~~~~~~~~~~~~~~~~~~~~
     | User not found_**

**Comment by cunninghamb505** [comment]
So did some digging with Sai and we think its because of the version of PowerShell. You need to ensure you have the correct version of each module in PowerShell. Anything higher and it will fail
4.1.0      Az 
1.9.4      Az.Accounts  
2.0.1      Az.Resources  
2.0.0      Az.KeyVault

**Comment by ginalee-dotcom** [comment]
Thank you for this! We also specified the version specifications in our README - we will update it accordingly.
