### ISSUE TITLE
FHIR Importer

### ISSUE THREAD

**Issue by Vikas-holla** [microsoft/fhir-server-samples#114]
Hi,

I have deployed azuredeploy-importer.json for fhir importer for our Azure API for fhir.  I have an issue that bundles are not getting loaded failing with the error. 

"AADSTS50059: No tenant-identifying information found in either the request or implied by any provided credentials.

I found this error message in fhirBundleBlobTriger monitor. Can you please tell me what went wrong.

Thanks and Regards!

**Comment by Vikas-holla** [comment]
I had skipped the default values in the JSON deployment file earlier, after entering the values and deployed again. Now the issue is different:

File read
Information
2021-01-14 15:16:16.130
Request failed with Forbidden. Waiting 00:00:02.0240000 before next retry. Retry attempt 1

There is not much information on why it is failing. Or is there a different log/error file that I need to look in. Sorry, I am a newbie for this. Can you please help in this.

Regards,
VH

**Comment by ginalee-dotcom** [comment]
What are the steps (i.e. commands you are running in order, including your subscription details and environment details) you are taking to produce this error?
Please re-open this issue with more information so that I can reproduce the error message - I'll keep it closed for now.
