### ISSUE TITLE
Running into error while setting up the demo

### ISSUE THREAD

**Issue by shikha1970** [microsoft/fhir-server-samples#121]
**Describe the bug**
.\Create-FhirServerSamplesEnvironment.ps1 -EnvironmentName mtcbang -UsePaaS $true                                        

When executing above line, line 67 in Create-FhirServerSamplesAuthConfig.ps , we are trying to access https://github.com/Microsoft/fhir-server/archive/$fhirServerVersion.zip which does not exist. 

Can you help me out with this.

**Comment by abhishek14anandDev** [comment]
Yes I am facing this too.

**Comment by tusv** [comment]
Ran into the same and couple more related issues. I have a PR out. https://github.com/microsoft/fhir-server-samples/pull/122

**Comment by ginalee-dotcom** [comment]
PR Merged.
