### ISSUE TITLE
Create-FhirServerSamplesEnvironment.ps1 gives resouorce not found

### ISSUE THREAD

**Issue by AhsanSAlam** [microsoft/fhir-server-samples#64]
I'm using the following command:
rverSamplesEnvironment.ps1 -EnvironmentName FHIRServerOS -EnvironmentLocation westus2 -UsePaaS $false -PersistenceProvider sql -SqlAdminPassword $(ConvertTo-SecureString -AsPlainText -Force "abcnnn")

At first, it provides the following warning after creating key vault:

WARNING: The provided information does not map to an AD object id.
WARNING: Access policy is not set. No user or application have access permission to use this vault. This can happen if
the vault was created by a service principal. Please use Set-AzKeyVaultAccessPolicy to set access policies.

Then come several errors with the first one "The Resource 'Microsoft.Web/sites/fhirserverossrvr' under resource group 'FHIRServerOS' was not found.

It seems something failed to create.

Any info would be helpful

**Comment by hansenms** [comment]
Please see this one:

**Comment by AhsanSAlam** [comment]
I still get the same error with lowercase name.... After looking at the error carefully, I may not be able to eastus2 for Azure SQL...


New-AzureRmResourceGroupDeployment : 12:04:46 AM - Resource Microsoft.ManagedIdentity/Identities 'default' failed with message '{
  "error": {
    "code": "ResourceNotFound",
    "message": "The Resource 'Microsoft.Web/sites/fhirserverossrvr' under resource group 'fhirserveros' was not found."
  }
}'
At C:\Data\Application Development\Samples\Complete FHIR Sample\fhir-server-samples\deploy\scripts\Create-FhirServerSamplesEnvironment.ps1:164 char:1
+ New-AzureRmResourceGroupDeployment -TemplateUri $sandboxTemplate -env ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [New-AzResourceGroupDeployment], Exception
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.ResourceManager.Cmdlets.Implementation.NewAzureResourceGroupDeploymentCmdlet

New-AzureRmResourceGroupDeployment : 12:04:53 AM - Resource Microsoft.Sql/servers 'fhirserverossrvr' failed with message '{
  "status": "Failed",
  "error": {
    "code": "ResourceDeploymentFailure",
    "message": "The resource operation completed with terminal provisioning state 'Failed'.",
    "details": [
      {
        "code": "ProvisioningDisabled",
        "message": "Provisioning is restricted in this region. Please choose a different region. For exceptions to this rule please open a support request with Issue type of 'Service and subscription limits'."
      }
    ]
  }

**Comment by hansenms** [comment]
That is a different error. I think this may be related to the issue with managed identity, which is mentioned here:

https://github.com/microsoft/fhir-server/issues/671

Could you try to just run the deployment a second time.

**Comment by AhsanSAlam** [comment]
Still the same error.

**Comment by hansenms** [comment]
I just tries in eastus and I am able to deploy and it is up and running.

**Comment by AhsanSAlam** [comment]
Did you use similar command as the one below from your desktop PowerShell or in Azure Cloud shell? Am I missing any other parameters?

Create-FhirServerSamplesEnvironment.ps1 -EnvironmentName FHIRServerOS -EnvironmentLocation westus2 -UsePaaS $false -PersistenceProvider sql -SqlAdminPassword $(ConvertTo-SecureString -AsPlainText -Force "abcnnn")

**Comment by AhsanSAlam** [comment]
Correction...

Create-FhirServerSamplesEnvironment.ps1 -EnvironmentName fhirserveros -EnvironmentLocation eastus -UsePaaS $false -PersistenceProvider sql -SqlAdminPassword $(ConvertTo-SecureString -AsPlainText -Force "abcnnn")

**Comment by AhsanSAlam** [comment]
It seems the script won't work for me. I'll try manual. The only thing I can think of is that AzureRM is running on a compatibility mode since I have already upgraded to Az module

**Comment by AhsanSAlam** [comment]
This was the last error I got... HTTP Error 502.5 - ANCM Out-Of-Process Startup Failure

**Comment by AhsanSAlam** [comment]
It seems it finally worked after I ran the script twice. Not sure how. Is it supposed to create 2 Key Vault resources?

**Comment by hansenms** [comment]
Yes, one KeyVault resource is for the OSS FHIR server deployment, the other one is for the demo environment details. 

The problem with having to run the template twice should be temporary, there is a bug that is being resolved related to managed identity.

**Comment by AhsanSAlam** [comment]
Thanks. this can be closed. I'll create a different thread if I encounter different issues or have questions. I'm now assessing the resources to test a few scenarios.

**Comment by hansenms** [comment]
@AhsanSAlam just FYI, the fix for the managed identity issue has just been merged in https://github.com/microsoft/fhir-server/commit/5fa767414c9ecbe170e918f5d94a93006cff1374 and I just tested that the fhir-server-samples scenario deploys without errors in eastus with the parameters you have before (I changed the environment name, but otherwise the same).

**Comment by AhsanSAlam** [comment]
Thank you for your help. I'll try it out.... This is very helpful since I'll be presenting at a meetup in couple weeks about Jumpstart with FHIR on Azure.
