### ISSUE TITLE
Growth Chart Code Deploy Failure

### ISSUE THREAD

**Issue by brochlabs** [microsoft/fhir-server-samples#71]
I was unable to redeploy/sync code from the repository for the growth web app, as I was encountering the following error:
npm ERR! Error: Method Not Allowed
npm ERR!        at errorResponse(<filepath>\add-named.js)....

I was able to resolve the issue by adding the 
"WEBSITE_NODE_DEFAULT_VERSION" application setting and assigning it a value of "8.10.0"

Please update the file below to include this app setting.

fhir-server-samples/deploy/templates/azuredeploy-smart-app.json

**Comment by hansenms** [comment]
This should be merged in now.
