### ISSUE TITLE
Unable to find type [System.Web.Security.Membership] error on macOS powershell

### ISSUE THREAD

**Issue by coolazeem** [microsoft/fhir-server-samples#73]
> Checking if UserPrincipalName exists
> User not, will create.
> Unable to find type [System.Web.Security.Membership].
> At /Users/azeemshaikh/Documents/Azure/fhir-server-samples/deploy/scripts/Create-FhirServerSamplesAuthConfig.ps1:160 char:17
> +    $password = [System.Web.Security.Membership]::GeneratePassword(16 ...
> + CategoryInfo          : InvalidOperation: (System.Web.Security.Membership:TypeName) [], RuntimeException
> + FullyQualifiedErrorId : TypeNotFound
 
**I'm running the script on macOS Mojave PowerShell 6.2.4**

**Comment by hansenms** [comment]
Yes, the `System.Web.Security.Membership` module is not part of PS Core on MacOS, so you should specify an admin password with something like `-adminPassword $(ConvertTo-SecureString -AsPlainText -Force 'MyPassword!!')`

**Comment by coolazeem** [comment]
Thank you! That worked
