### ISSUE TITLE
Powershell script to update the commandlet for Get-AZADUser

### ISSUE THREAD

**Issue by sowsan** [microsoft/fhir-server-samples#74]
Deployment scripts are using Instead of Get-AzureADUser and it seems the latest PowerShell is using
Get-AzADUser and there are lot of parameter changes. Is any updated deployment script available to use?

**Comment by hansenms** [comment]
Can you clarify. What is the issue is? There are two different modules `AzureAd` and `Az` they are both needed. The AzureAd stuff we do with the `AzureAd` module, which must be installed.

**Comment by sowsan** [comment]
Thank you @hansenms . That worked. I was using only the Az module. Any specific permission needed on the AAD tenant to complete user creation operation?
