### ISSUE TITLE
Create-FhirServerSamplesEnvironment.ps1 ignores -EnvironmentLocation flag

### ISSUE THREAD

**Issue by mikemassa84** [microsoft/fhir-server-samples#83]
Not all resources created when running the Create-FhirServerSamplesEnvironment.ps1 script are created in the location specified by the -EnvironmentLocation flag.

The Azure API for FHIR is created in `West US 2`.
The Application Insights is created in `East US`.

We ran the following:
`Create-FhirServerSamplesEnvironment.ps1 -EnvironmentName nma1-fhir -UsePaaS $true -EnableExport $true -EnvironmentLocation NorthCentralUS`

**Comment by hansenms** [comment]
It is not exactly ignoring it. But ApInsights is not available in all regions, so we just create it where it is. But the other resources go where you specify.

**Comment by mikemassa84** [comment]
AppInsights is available in NorthCentralUS though, which is where we are specifying. Same goes for the Azure FHIR API.

**Comment by hansenms** [comment]
We don't do a check to see if AppInsights is available in the region you are trying to use. We just place it in east us. This is a demo environment. For the purposes of a demo, it does not matter where it is. If it is important, please clone the repo and edit it.

Also not that this is a demo, not a production environment, so you will likely have to make several other adjustments. Use it as inspiration.
