### ISSUE TITLE
403 response when trying to access resources

### ISSUE THREAD

**Issue by ruudz** [microsoft/fhir-server-samples#84]
I have a problem after setting up the open source FHIR Server for Azure. I followed the steps as described in the README yet when I open the dashboard I get a 403 response when trying to fetch the Patients. The token seems to be generated (I logged in using the same account I used to setup the environment on Azure).

So I saw #66 and tried to see if the solutions there would help. I tried to see if my account had the proper roles and added myself as owner of the `<name>srvr.azurewebsites.net` App in Azure Active Directory. Now, I am an absolute newbie when it comes to Azure so I'm not sure if I did it the proper way but it did not solve things. 

So I tried to follow the instructions here: https://docs.microsoft.com/en-us/azure/active-directory/develop/v1-oauth2-client-creds-grant-flow and I am able to generate a token but still I get a 403 when trying to access the API endpoints (also in Postman).

Does anyone have an idea what I'm doing wrong? Any help is greatly appreciated!

**Comment by hansenms** [comment]
In general, a 403 means that you have a valid token in terms on authority (issuer) and audience, but the user or service principal that the token is issued for does not have access.

Since you are using the OSS server, you need to have the right roles. So adding yourself as "owner" of the app will not do it. You need to go to the enterprise application for the FHIR API and then in users and groups give your user the right role:

![image](https://user-images.githubusercontent.com/1149740/84923188-be655780-b07b-11ea-803e-d920dca5ce27.png)

You can validate that you have been assigned a role by checking your token (with something like https://jwt.ms) and check the roles claim.

**Comment by petersontylerd** [comment]
What a timely thread. I've been struggling with this all morning. Exact same problem, and this solution worked perfectly. Thanks Michael.

**Comment by ruudz** [comment]
@hansenms, thank you for the quick response. I tried to find the right location to add users but what I'm seeing differs slightly from your screenshot (maybe something to do with subscription?).

![1](https://user-images.githubusercontent.com/2395361/85022485-a7a22c00-b173-11ea-8a3a-ee373191b1cb.png)

I did however find it and added my user, tried to get a new token but it seems I'm not assigned a role (according to https://jwt.ms). Using the token to make a request still results in a 403. I'm only able to assign the `Default Access` role to a user though. Any ideas? Thanks in advance!

**Comment by hansenms** [comment]
Do you have app roles defined for your resource application. From your screenshot, it looks like it is not the app generated by the deployment, since the display name would be the URL of the FHIR server.

**Comment by vpatil85** [comment]
@hansenms  I'm struggling with exact same issue (403 forbidden) at the moment with FHIR OSS setup. I'm unable to find app with URL name (https://**fhirserver**.azurewebsites.net) instead, I see an AAD app with the name **fhirserver** after turning on the system assigned identity. 

Please advise.

**Comment by vpatil85** [comment]
Thanks for confirming on system assigned identity piece. I had turned it on for FHIR API web app of OSS. 
On the other hand, I do not quite see the resource application in my AAD that you are referring here. I have manually created two app registrations namely for FHIR server & FHIR client app and assigned scope & roles as per following documentation. The FHIR client app registration has been granted admin role on FHIR server app registration. Am I missing something here?

https://docs.microsoft.com/en-us/azure/healthcare-apis/register-resource-azure-ad-client-app

**Comment by hansenms** [comment]
You should be able to see it in AAD application registrations:
![image](https://user-images.githubusercontent.com/1149740/85057658-e88b4800-b155-11ea-8a36-91c1c05c54af.png)
Remember to switch to all application and you might need to search.

**Comment by vpatil85** [comment]
There are the only app registrations I could see under all applications. The circled in green are the ones we used for configuring security on FHIR web app for OSS. 

![image](https://user-images.githubusercontent.com/43274684/85060536-6742ae00-b173-11ea-82fb-aee39787093b.png)

**Comment by hansenms** [comment]
Those app registrations are not the ones that generated by this environment. Did you actually deploy the samples environment or just a FHIR server independently.

**Comment by vpatil85** [comment]
We deployed an independent FHIR server with Azure SQL as a back end data store. I should have probably asked this under FHIR server thread. However, we see the exact same issue with our install as well.

**Comment by hansenms** [comment]
The role should be called `globalAdmin` for the fhir-server. See the list of "default" roles in https://github.com/microsoft/fhir-server/blob/master/src/Microsoft.Health.Fhir.Shared.Web/roles.json

**Comment by ruudz** [comment]
@hansenms, I do see one in App Registration: 
![image](https://user-images.githubusercontent.com/2395361/85105392-c43d7300-b20a-11ea-80fc-ec6c4400b2f7.png)

But I do not have the option to manage roles like in your screenshot:
![image](https://user-images.githubusercontent.com/2395361/85105660-1b434800-b20b-11ea-96a6-68c06fa3f37d.png)

**Comment by hansenms** [comment]
You should see any roles in the manifest. I am not sure what the "Roles and administrators (preview)" tab actually does, but it is not where you define app roles as far as I know. I would look at the manifest. It is a JSON document. You should see a field called `appRoles` in there.


You can then click to the managed application:

![image](https://user-images.githubusercontent.com/1149740/85207350-734e7d00-b2e5-11ea-9577-1a94d8cbda08.png)

And then manage the users and groups that are assigned (like described above):

![image](https://user-images.githubusercontent.com/1149740/85207361-8f521e80-b2e5-11ea-9245-657635e57869.png)

**Comment by ruudz** [comment]
@hansenms, excellent! I finally found the right screen. :sweat_smile: I was able to add a user and the request seem to work properly now. Thanks again for your help!
