### ISSUE TITLE
error creating resource

### ISSUE THREAD

**Issue by rramosj2** [microsoft/fhir-server-samples#85]
I followed the readme instructions with both a new tenant and an existing one and I am getting the following error - script continues and fives me a url but no resources are created.
`.\Create-FhirServerSamplesEnvironment.ps1 -EnvironmentName fhirj2rr -UsePaaS $false
Current context is user: XXXXXX
fhirj2rr
FhirServer PS module is loaded
Creating keyvault with the name fhirj2rr-ts
Current context is user: rramos@j2interactive.onmicrosoft.com
Adding permission to keyvault for 595750b9-846e-4f16-afa6-7f5ed5f5fa60
Ensuring API application exists
Checking if UserPrincipalName exists
User not, will create.
New-AzureADApplicationPasswordCredential : Error occurred while executing GetApplication
Code: Request_ResourceNotFound
Message: Resource 'ad29f0f6-8669-4d88-8a07-a070a4569434' does not exist or one of its queried
reference-property objects are not present.
RequestId: 3d84ab92-0d1c-4125-87fd-371a37c3bcb5
DateTimeStamp: Wed, 17 Jun 2020 19:35:11 GMT
HttpStatusCode: NotFound`

**Comment by hansenms** [comment]
Are you using a different AAD tenant for your Azure subscription and the data plane?

**Comment by rramosj2** [comment]
Hi Michael,
I am yes, I created a new AAD tenant and moved the subscription over. This was about 1 hour ago. I was getting issues earlier with the original AAD (I did have owner rights) and the script was having issues with the keyvault as well..
does the loginAz-Account cmd know how to differentiate between accounts?

**Comment by hansenms** [comment]
Hmm...I have not tried the scenario of moving the subscription over so we may be in uncharted waters here.

The concept here is that we use the `AzureAd` module to set up things in the AAD tenant that controls access to the data plane. And we use `Az` module to provision resources. The AAD tenant for the dataplane and the one for the subscription can be the same but don't have to be. 

You should make sure you select the right subscription....using `Select-AzSubscription ...` if you have multiple subscriptions tied to the tenant you log into with `Login-AzAccount`. Could that be it?

Also, you may want to clean out any resource groups that you have created with any prior attempts, if it finds an KeyVault with "old" tenant details it will start trying to update those applications and that could fail.

**Comment by rramosj2** [comment]
I only have one subscription with 2 tenants. When I do the Login-AzAccount , it still displays the old tenant but the Connect-AzureAd -TenantDomain does work.
I did have a previous instance of the FHIR server installed as I was testing it before on its own. I'll try to clean up the old version and start from scratch.
Thanks

**Comment by hansenms** [comment]
Also try to do `Clear-AzContext` a few times to make sure you sign in the right place.

You cannot have one subscription with two tenants, so there may be some misunderstandings too. A subscription is always tied to a single tenant. The same tenant can have multiple subscriptions or it can in fact have no subscriptions at all if you are just using it for data plane.

**Comment by rramosj2** [comment]
I finally created a new subscription and did a few Clear-AzContext as suggested and it worked. Thanks!
If I may ask a couple of questions on your devdays presentation you mention that there is a sample Datafactory that can show transforming the data. Is that available anywhere that we could use as a starting point to build on?

**Comment by hansenms** [comment]
We used to use Data Factory in this samples environment for export, but now that the service supports `$export` we just use that.

**Comment by rramosj2** [comment]
Thanks! I did create it with the Export flag. I'll explore a bit.
Could I bug you for one more question?
I am trying to post a bundle from the Synthea project to the \Bundle end point of my server. I get a 201 created but the individual resources are not found when I do a \Patient\{id} for example
do you know what could be the problem?
I tried to change type from transaction to batch and tried a simple bundle from the fhir site too.. same result

**Comment by hansenms** [comment]
If you want to post a bundle, you need to do it to the root endpoint (please read spec). For the managed service, we only support bundles of type batch. For transaction bundles, use the OSS server with SQL persistence provider. 

I’m gonna close this issue. If you have issues with the FHIR server, please post them on that repo.
