### ISSUE TITLE
Build FhirDashboard from VS Code

### ISSUE THREAD

**Issue by RahulKate** [microsoft/fhir-server-samples#88]
I tried to build FhirDashboard javascript project from Visual Studio Code and found config issue as,

Need config file **(/.auth/me)** which is mentioned in below code snippet,

![image](https://user-images.githubusercontent.com/13742253/90798319-6bd04200-e32f-11ea-93d6-c4d9cd7ac7ea.png)

I am able to successfully launch dashboard application as, but config file is not present so not able to get details,,,

![image](https://user-images.githubusercontent.com/13742253/90798545-b05bdd80-e32f-11ea-8a39-15954a91826c.png)

Please provide the same file and any other dependency so I can build from outside..

**Comment by hansenms** [comment]
That file is only available when running in an Azure Web app. You can simulate it locally by setting up a web app with appropriate configuration and then copy that file locally.

**Comment by RahulKate** [comment]
Do you mean that, first I need to deploy FHIR server samples to azure and then I can get the same file or file format from azure web app....?

**Comment by hansenms** [comment]
Well you can really deploy any web app and switch on [app service authentication](https://docs.microsoft.com/en-us/azure/app-service/overview-authentication-authorization).

The javascript app itself does not have any of the auth flow code. We just leverage that from App Service here. I admit, it makes it annoying to work with locally, so maybe that should be changed.

**Comment by venkateshtarra** [comment]
Hi Team,

I have deployed FHIR samples using script but I am unable to load dashboard site which is showing as loading forever.
 
.\Create-FhirServerSamplesEnvironment.ps1 -EnvironmentName fhirazure -UsePaaS $true -EnableExport $true

![image](https://user-images.githubusercontent.com/79094431/122089906-ddc8c900-ce24-11eb-9c43-1ff754a4b95c.png)
