### ISSUE TITLE
Create-FhirServerSamplesEnvironment.ps1 failing to run as documented 

### ISSUE THREAD

**Issue by daemel** [microsoft/fhir-server-samples#89]
Trying to use the command below by reading through the script, here are the issues.

1)  Script defaults back to WestUS and WestUS2

2) Scrip does not process the SQL Admin Password 

Create-FhirServerSamplesEnvironment.ps1 -EnvironmentName uh-test-api -EnvironmentLocation eastus -FHIRApiLocation eastus -UsePaaS $false -PersistenceProvider sql -SqlAdminPassword nimda1234 -AdminPassword nimda6789 -EnableExport $true

**Comment by hansenms** [comment]
`AdminPassword` and `SqlAdminPassword` are "SecureString" parameters, so you cannot pass in a string, you have to pass in a secure string, so something like:

```powershell
Create-FhirServerSamplesEnvironment.ps1 -EnvironmentName uh-test-api -EnvironmentLocation eastus -FHIRApiLocation eastus -UsePaaS $false -PersistenceProvider sql -SqlAdminPassword $(ConvertTo-SecureString -Force -AsPlainText 'nimda1234') -AdminPassword $(ConvertTo-SecureString -Force -AsPlainText 'nimda6789') -EnableExport $true
```

The parameter is `FhirApiLocation` (not `FHIRApiLocation`) and I am not sure it is passed to the OSS template, so you may need to go spelunking through there and figure out how that is set. I would assume it is based on the location of the RG if nothing is set, but could be wrong. Either way, it is meant for the FHIR API when using the managed service.
