### ISSUE TITLE
[Question] Auth options

### ISSUE THREAD

**Issue by medlab001** [microsoft/fhir-server-samples#95]
FHIR server uses Azure AD to authenticate clients, but I'm also interested in creating a patient self-help portal, where they can manage, update and change their medical info. Does this mean I'll have to create new AD account for all of the users? Or must I add another API on top of the FHIR server that proxies/forwards all to it to manage user auth? 

I was hoping this would help with the creation of a new example, or some help regarding what direction to take to implement patient login functionality?

**Comment by brochlabs** [comment]
Azure B2C is designed for this type of workflow, although you would need to create an api to be called in an auth flow that would allow for correlation between the patient I’d and the new ad user

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by medlab001** [comment]
Ahh, I see, I missed this. Thanks for that!
If I'd rather use my way of authentication/authorization, how do I handle that?

**Comment by brochlabs** [comment]
If you can share some details, I can point you in the right direction, but ultimately with any auth mechanism, you’ll need a way to tie an external claim to the patient record. Using oAuth with an external IDP, like gmail/etc still requires that the system accepting the claim match it to a user configured with the system. AzureB2C handles this by automatically creating that user upon enrollment

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by medlab001** [comment]
Details, well I'm still starting out with this, so I'm actually looking for info on how to accomplish this. From your suggestion, I could use B2C for this, and seems to meet all the requirements, such as user types for access control. In case I go ahead with B2C, how do I tie a user's info to the B2C account? I'll need an API b/w B2C and FHIR server, correct? This API will be the one that checks that the user is authorized to view that information.

I'll clarify a custom solution once I'm up to speed with B2C usage. Thanks for your help!

**Comment by medlab001** [comment]
@brochlabs 
I was able to configure Azure B2C, thanks for the info! With that directly connected to FHIR server, I can see all the info. 
This [page](https://docs.microsoft.com/en-us/azure/healthcare-apis/use-custom-headers) suggests that external auth is required for fine-grained access, such a patient being able to access only their data. My idea was to use Ocelot to inspect the tokens, (and extended permissions stored, say in CosmosDB) and then forward the request to the FHIR server. Have I got this right?

**Comment by brochlabs** [comment]
Essentially yes. I would recommend that you CISO sign off on your final
authentication and authorization pattern, but yes, the first piece there
would be to determine what your system of record is for determining whom
has authorization to a patient record. For example, the EMR or the FHIR
server should be the most up-to-date system of record for determining a
patient or their authorized contact ( oftentimes you have a legal guardian,
parent, or someone whom has power of attorney that would be authorized to
view the patient record). On initial authentication, you need a mechanism
to query not only the authenticating person's EMR ID, but also their
related contacts. You could then store those tokens in Redis Cache so they
are available for the session context, etc.

**Comment by medlab001** [comment]
Yeah this is starting to make sense. 
But I ran into an issue. I'm using the `Azure API for FHIR`, so can't customize the auth pattern there much. For each incoming request, token validation isn't enough. I'll need to check if an physician can view a corresponding patient's data, but there's no such info on the server. If I understood you right, I store this mapping elsewhere, such as a `<insert DB + private API, perhaps>` and then query it for the given request, and conditionally forward it to FHIR, correct? The trick here, that I must be careful about, is that on new 'relation' (such as a patient being assigned a physician), I must first update my setup, and then update FHIR, so that I'll know what patients to retrieve given a physician. Not sure if I can use Redis here, since it might lose data when there's a crash.

Do let me know if I've got this right. 

Thank your very much for your kind help, it's been really invaluable in clarifying how things work, and how I'm supposed to integrate all these.

**Comment by brochlabs** [comment]
Correct, determining whom has access to a patient's record requires
constraints implemented beyond the FHIR API. The Redis cache was more for
retrieving that information and storing it for the context of the session,
but you are correct, there needs to be a source system for
controlling/requesting/assigning access to a patient record. There is the
potential that you could store this information within the FHIR API, using
the RelatedPerson endpoint, but I haven't vetted that out yet, and it will
be a few days before I can circle back to my API environment.

[image: image.png]

**Comment by medlab001** [comment]
Thank you for clearing that up! 

In B2C, I'm trying to bind the FHIR ID in the user's claims after they register, so that after they login, I can get their FHIR token directly. 

![image](https://user-images.githubusercontent.com/72015764/96113853-642db380-0f02-11eb-92c7-cf738b3ff110.png)

I do get the ID in the token `"extension_FHIRID": ""`, after they signin, but I am trying to update it through the graphAPI. The GraphAPI docs only talk about how to create '[open extensions](https://docs.microsoft.com/en-us/graph/api/resources/opentypeextension?view=graph-rest-1.0)' which are different from extension attributes. I can fetch these through the GraphAPI (`_graphService.Users[claimsIdentity].Request().Select($"extension_{b2c-app-id}_{id_name}").GetAsync();`), but I can't find any resources on hot to modify them. Could you kindly point me to the right resource? 

Have a great day!
