### ISSUE TITLE
Better Warning, Replacement, or Removal or FHIR Admin User Password Generation

### ISSUE THREAD

**Issue by mikaelweave** [microsoft/fhir-server-samples#97]
**Overview**
I'm currently going through the [FHIR OpenHack](https://github.com/microsoft/OpenHack-FHIR) on my Mac. When running `Create-FhirServerSamplesEnvironment.ps1` I get the below error.

![image](https://user-images.githubusercontent.com/753437/95239360-b1ea4380-07bf-11eb-9e17-dde97caa07ea.png)

I know there is [already an issue around this](https://github.com/microsoft/fhir-server-samples/issues/73), but I think changing the code to make the script usable without reading the issues would be a better experience for new developers using a *nix OS.

**Thoughts for a fix**
- Easiest solution would be to check for the existence of the library on the system and throw a more user friendly message if it cannot be found. This message should instruct the user to add the `AdminPassword` parameter.
- Second possible solution would be to replace it with a different, cross-platform approach. This may require adding another function to the module/script as there isn't a equal method in .NET Core (see below for more).
- Third solution would be to just remove the automatic password generation, and force the user to always supply it. I think the best arguments for this are in a [.NET Core issue about replacing the Windows library](https://github.com/dotnet/aspnetcore/issues/19653).

**Comment by ginalee-dotcom** [comment]
Thank you for the feedback! Will work on this.
