### ISSUE TITLE
Fhir Importer fails to import large batches: Cosmos PUTs rejected due to high request count; messages end up in poison queue

### ISSUE THREAD

**Issue by nmiodice** [microsoft/fhir-server-samples#98]
After generating data using `java -jar synthea-with-dependencies.jar -m "covid19" -p 50` and placing the files in the import storage container, the importer function will attempt to import the files at an extremely high rate. This causes a ton of the following errors (from the function app logs):

```bash
2020-10-06T20:49:11.354 [Warning] Request failed with TooManyRequests. Waiting 00:00:08.0310000 before next retry. Retry attempt 4
...
2020-10-06T20:49:15.438 [Error] Executed 'FhirBundleBlobTrigger' (Failed, Id=8c069d01-5689-4376-9d81-6a4bc2d512c4, Duration=24264ms)Unable to upload to server. Error code TooManyRequests
```

Eventually, the following is logged and the function app no longer attempts to import the files:
```bash
2020-10-06T20:49:15.499 [Warning] Message has reached MaxDequeueCount of 10. Moving message to queue 'webjobs-blobtrigger-poison'.
```

Better throttling in the function app would allow it to consume the generated payloads at a slower rate and would not result this type of failure.

**Comment by nmiodice** [comment]
For reference, I'm following the steps here: https://github.com/microsoft/OpenHack-FHIR/tree/main/Challenge01-AzureAPIforFHIR#option-2-generate-synthea-data

**Comment by hansenms** [comment]
Scale up your DB.....or scale down the function.

**Comment by nmiodice** [comment]
I'm assuming that the application is intended to work out of the box, alongside the referenced open-hack material. Would this be correct?

Are you suggesting that the fix should be to change the default scaling options for Cosmos or the function app in the referenced openhack content?

**Comment by hansenms** [comment]
The application "works out of the box" but it is a sample application of how something _could_ be done and not meant as production code that can handle any scenario. It was not developed for the open hack scenario as such. So depending on how the code is used, it may make sense to adjust some settings. Specifically on scaling, the deployment is optimized to be low cost (for development purposes), but if you want to scale to higher workloads, you may need to adjust some parameters. 

So I don't think the default settings should be changed here, but maybe the open hack instruction should include instructions on how to scale things appropriately.

**Comment by nmiodice** [comment]
Thank you for clarifying that the content in this repository is not intended to be specifically used for the Open Hack material. I'll check to see where in that repository it makes sense to add instructions about how to deal with this scenario.

Thanks!
