### ISSUE TITLE
Consider App role rename

### ISSUE THREAD

**Issue by pjirsa** [microsoft/fhir-server-samples#99]
https://github.com/microsoft/fhir-server-samples/blob/56148a7450c2d6c913f69a86509060c57b9bc5a1/deploy/scripts/Create-FhirServerSamplesAuthConfig.ps1#L138

"globalAdmin" is a bit ominous for any IT security folks and in this case doesn't equate to true "global admin" access for the AAD tenant. 

Consider changing name of app role to something like: "ReadWrite.All" or similar.

**Comment by pjirsa** [comment]
related: https://github.com/microsoft/fhir-server/issues/1421

**Comment by ginalee-dotcom** [comment]
Closed per https://github.com/microsoft/fhir-server/issues/1421
